---
- name: Turn Firewall OFF
  hosts: all
  become: true
  tasks:
    - name: Stop and disable firewalld service
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false
