---
- name: Turn Firewall ON
  hosts: all
  become: true
  tasks:
    - name: Start and enable firewalld service
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
